__title__ = 'MetaDoc'
__package_name__ = 'metadoc'
__author__ = 'Michael Delgado'
__description__ = 'Tools for documentation-aware data reading, writing, and analysis'
__email__ = 'delgado.michaelt@gmail.com'
__version__ = '0.0.1'
__license__ = 'MIT'
__copyright__ = 'Copyright 2016 Michael Delgado'
