__title__ = 'MetaCSV'
__package_name__ = 'metacsv'
__author__ = 'Michael Delgado'
__description__ = 'Tools for documentation-aware data reading, writing, and analysis'
__email__ = 'delgado.michaelt@gmail.com'
__version__ = '0.1.1'
__license__ = 'MIT'
__copyright__ = 'Copyright 2016 Michael Delgado'
