# Config file for automatic testing at travis-ci.org
# Based on https://github.com/pydata/xarray/blob/master/.travis.yml

language: python

# sudo: false # use container based build
notifications:
  email: false


matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
      - CONDA_ENV=py27-min
      - status=min
  - python: 3.4
    env:
      - CONDA_ENV=py34-min
      - status=min
  - python: 3.5
    env:
      - CONDA_ENV=py35-min
      - status=min
  - python: 3.6
    env:
      - CONDA_ENV=py36-min
      - status=min
  - python: 2.7
    env:
      - CONDA_ENV=py27
      - status=latest
  - python: 3.4
    env:
      - CONDA_ENV=py34
      - status=latest
  - python: 3.5
    env:
      - CONDA_ENV=py35
      - status=latest
  - python: 3.6
    env:
      - CONDA_ENV=py36
      - status=latest
  - python: 3.6
    env:
      - CONDA_ENV=py36-xarray-dev
      - status=dev
  - python: 3.6
    env:
      - CONDA_ENV=py36-pandas-dev
      - status=dev
  allow_failures:
  - python: 3.6
    env:
      - CONDA_ENV=py36-pandas-dev
      - status=dev
  - python: 3.6
    env:
      - CONDA_ENV=py36-xarray-dev
      - status=dev
  - python: 3.6
    env:
      - CONDA_ENV=py36-min
      - status=min

services:
  - docker

before_install:
  - docker pull continuumio/miniconda
  - docker run -i -t continuumio/miniconda /bin/bash

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - if [[ "$status" == "latest" ]]; then
      conda env create -n $CONDA_ENV python=$TRAVIS_PYTHON_VERSION;
      conda install -n $CONDA_ENV --file ci/requirements-latest-conda.txt;
      source activate $CONDA_ENV;
      python -m pip install -r ci/requirements-latest.txt;
    else
      conda env create --file ci/requirements-$CONDA_ENV.yml;
    fi
  - source activate $CONDA_ENV
  - python setup.py install

script:
  - python -m pytest

after_success:
- coveralls
