# Config file for automatic testing at travis-ci.org
# Based on https://github.com/pydata/xarray/blob/master/.travis.yml

language: python
dist: xenial

notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 3.7
    env:
      - CONDA_ENV=py37-min
      - STATUS=min
  - python: 3.6
    env:
      - CONDA_ENV=py36-min
      - STATUS=min
  - python: 3.6
    env:
      - CONDA_ENV=py36
      - STATUS=latest

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

install:
  - if [[ "$STATUS" == "latest" ]]; then
      conda create -n $CONDA_ENV python=$TRAVIS_PYTHON_VERSION;
      conda install -n $CONDA_ENV --file ci/requirements-latest-conda.txt;
      source activate $CONDA_ENV;
      python -m pip install -r ci/requirements-latest.txt;
    else
      conda env create --file ci/requirements-$CONDA_ENV.yml;
    fi
  - source activate $CONDA_ENV
  - python setup.py install

script:
  - source activate $CONDA_ENV
  - python -m pytest

cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

after_success:
- coveralls
